# Generated by Django 5.2.6 on 2025-09-10 22:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinarian', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinarian',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
